version: "3.7"
services:
    # image project
    crud_kpmg:
        build: 
            args: 
                user: jpls
                uid: 1001
            context: ./
            dockerfile: Dockerfile
        container_name: app
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - crud_kpmg
    
    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports: 
            - 8989:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - crud_kpmg

    # db mysql
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3388:3306
        networks: 
            - crud_kpmg
    
    #adminer
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080

networks: 
    crud_kpmg:
        driver: bridge